### ISSUE TITLE
Batch requests

### ISSUE THREAD

**Issue by petero-dk** [kendarorg/PhpNuget#22]
I have noticed when using many packages, Visual Studio will batch requests into one. This batch request is unsupported in PhpNuget,

I have tried to disseminate the request and implement it, however unsuccessful.

My efforts are documented here:
https://github.com/ecomerc/PhpNuget/commit/ed38ae1cbf40f41169b6b28638a0825f75064907

Perhaps someone can see where I am going wrong?

**Comment by petero-dk** [comment]
More information about the batch request:

http://inedo.com/support/questions/2451
https://www.jfrog.com/jira/browse/RTFACT-5248

Implementations:

http://blogs.msdn.com/b/webdev/archive/2013/11/01/introducing-batch-support-in-web-api-and-web-api-odata.aspx
themotleyfool/NuGet.Lucene@4c33fd0

**Comment by kendarorg** [comment]
Thanks :+1:  i did'nt even knew this existed! Will get it working shorty hopefully :O

**Comment by kendarorg** [comment]
Better description of the protocol: https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch

**Comment by kendarorg** [comment]
I added a possible solution. Even if i have not yet understood how to test it "for real"!
If you look at src/api/v2/batch.php at line 118 you can find the comment "//WRITE_FILE" if you can write down on a file the content of the $input variable (so that i can verify if it corresponds!)

**Comment by willemda** [comment]
Thanks for the great info here, didn't know this behavior.

@kendarorg, 
From my understanding NuGet will make a batch request it detect the query string is too long (prob. over 1000 chars). For testing purposes, you can generate such long query string by referencing a lot of old nuget package and doing a NuGet Update (https://docs.nuget.org/consume/command-line-reference#update-command), I suppose NuGet will then switch to batch requests.

I'll try to add support for it as well (https://github.com/willemda/Nusharp)

**Comment by kendarorg** [comment]
@petero-dk , @willemda : The actual implemenation can retrieve the data following the batch request. The only issue now is what nuget is expecting!

**Comment by kendarorg** [comment]
@willemda : The present release works...at least reading the multipart/mixed data from a C# program..
I tried to make a search via the nuget VS plugin using as search string 1600 characters long (1200 was not working). The problem, founded thanks to fiddler, is that (1st) nuget.org does not respond to the request (2nd) phpnuget respond but the nuget hangs :O do you have some clue

**Comment by kendarorg** [comment]
@petero-dk , @willemda : now working on the nuget v2 source to understand what is its $batch "style"

**Comment by kendarorg** [comment]
Now it does not hang Visual Studio 2014, but the response to the batch is not recoginzed...

**Comment by kendarorg** [comment]
@petero-dk : The responses and the results seems corresponding now to what is expected by nuget server client. I tried with the Simple.OData.Client and a C# test program, all seems working.

I used for test the description of the package http://www.nuget.org/api/v2/package/Bytescout.BarCode/2.3.0.457 that is pretty long (the block that starts with "- Supports 1D barcodes.." until the end of line.

The code i used to test is the following. 

```
private static void OdataBatchRequest(){
    var longDescription = ""; //see the package
    var host = "http://localhost:8020/phpnuget/api/v2";
    //var host = "http://www.nuget.org/api/v2";
    IEnumerable<dynamic> data = null;

    var x = ODataDynamic.Expression;
    var batch = new ODataBatch(host);
    batch += new Func<IODataClient, Task>(async c =>
    {
        data = await c
            .For(x.Packages)
            .Filter(x.Description.Contains(solong) == true)
            .FindEntriesAsync();
    });

    var result = batch.ExecuteAsync();
    result.Wait();

    foreach (var package in data)
        Console.WriteLine(package["Description"].ToString().Substring(0, 40));
}
```
