### ISSUE TITLE
Issue with package upload

### ISSUE THREAD

**Issue by bartekx** [kendarorg/PhpNuget#27]
I'm uploading package by nuget command line tool, on Ubuntu 14.04 / mono: 
```nuget push Xxxx.nupkg -Source http://myserver/phpnuget/upload```
I noticed that this file after uploading, in packages directory, have 1 byte more than file I have locally. That is causing an error when I'm trying to install this package by VisualStudio Package Manager or NuGet Package Explorer. That byte is ```0A```

**Comment by kendarorg** [comment]
Hi, but you upload through mono? What version of nuget and mono?
I tried uploading with nuget from windows and everything seems ok :O
Waiting for more infos :)

**Comment by bartekx** [comment]
I have NuGet v2.8.5 and configured this way:

/usr/bin/nuget :

```#!/bin/sh
exec /usr/bin/mono --runtime=v4.0.30319 --gc=sgen /opt/nuget/nuget.exe "$@"
```
Mono version:
```Mono JIT compiler version 4.0.1 (tarball Tue Apr 28 11:47:58 UTC 2015)```

**Comment by kendarorg** [comment]
Thanks :)
