### ISSUE TITLE
Case insensitive API search

### ISSUE THREAD

**Issue by crt** [kendarorg/PhpNuget#49]
Hi,

I am using 4.0.0.0 version for a local chocolatey repo and have a problem with case sensitivity.

I created a FirefoxESR packages based on the original chocolatey template file:
https://chocolatey.org/packages/FirefoxESR

However, chocolatey cannot download the nuget package because it searches for 'firefoxesr' not 'FirefoxESR' and the server doesn't find it. 

It can be tested with a simple curl command, this works:
curl "http://localhost/choco/api/v2/Packages(Id='firefoxesr',Version='45.5.1')"
but this doesn't:
curl "http://localhost/choco/api/v2/Packages(Id='FirefoxESR',Version='45.5.1')"

I would prefer not to touch anything in the original template file but the download url which points to a local webserver.
Would it be possible to make the query of the package id case insensitive or to add an option to do so?

Thank you,
Zoli

**Comment by kendarorg** [comment]
Fixed on 4.0.0.1
