### ISSUE TITLE
Version 4.0.0 - Bug in src/assets/route.js

### ISSUE THREAD

**Issue by bkraul** [kendarorg/PhpNuget#52]
There is a bug on line 13 of ```src/assets/route.js``` which causes requests to be made to files with extension .html instead of .php, which causes 404 errors. 

Per the rest of the calls in the file, the line:
```php
templateUrl: pathHelper.buildViewsPath('home/home.html'),
```
Should be:
```php
templateUrl: pathHelper.buildViewsPath('home/home.php'),
```

**Comment by kendarorg** [comment]
Well, it is actually correct, since it's really an html file :)
