### ISSUE TITLE
Since 3.0.12.11 setup.php seems to not working

### ISSUE THREAD

**Issue by windischb** [kendarorg/PhpNuget#53]
With version 3.0.12.9 i can use the setup.php to set admin username and password.
After that i can login with that credentials.
Since 3.0.12.11 that doesn't work for me.
I cant set username and password, but afterwards i can't login with them...

**Comment by windischb** [comment]
Ok, it hasn't worked because of missing Permissions on directories...
But the next Problem is that i can't get it to ru nwith Visual Studio 2017.
I'll only get 404 errors

**Comment by kendarorg** [comment]
Fixed on 4.0.0.1

**Comment by kendarorg** [comment]
Should use the path http://[yourhost:port]/[yourpath]/api/v2/ in nuget configuration
