### ISSUE TITLE
DockerFile V4.0.0.2 from tutum/apachephp

### ISSUE THREAD

**Issue by DrOuSS** [kendarorg/PhpNuget#59]
Hello,

We have tried to upgrade php nuget version  from 3.0.12.2 to 4.0.0.2 in this docker file https://hub.docker.com/r/bwaller/phpnuget/~/dockerfile/

We can push nupkg file from nugetpackageexplorer v4.1.32
Within the web site we can refresh repository (Go button)
We can see all package within manage package tab

But we can't get packages  listing from Visual studio or nugetpackage explorer. We have this error : 
The V2 feed at 'http:xxxx/phpnuget/api/v2/Search()?$filter=IsAbsoluteLatestVersion........ returned an expected status code '404' not found

We have also tried to create dockerfile with last tls ubuntu v16.04 with apache2 and php7 with nugetphp 4.0.0.2, we have the opposite behaviour.
We cannot push any package (Go button, do nothing)
We have no error when getting empty list using visual studio or nugetpackageexplorer

Best regards

DrOuSS

**Comment by laurentKTR** [comment]
hi
i'm working with @DrOuSS on the subject
i finally end up fixing some missing tools in php 7  ( php-zip && php7.0-xml were missing)
So we have a dockerfile from ubuntu 16.04 and apache 2 php 7
we can upload a nupkg file from your website, 
the tab package list the uploaded package
but i still don't have any package using vs2017, no error are returned

**checking** /var/log/apache2/error.log => nothing 

**checking** /var/log/apache2/access.log
GET /api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net461'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0 HTTP/1.1" 200 813 "-" "NuGet Client V3/4.5.0 (Microsoft Windows NT 10.0.16299.0, VS Community/15.0)
=> 200 but no list

in vs 2017 i have opened Package Manage Console
Install-Package AdvancedConsoleTraceListener -Version 1.0.0

Retrieving package 'AdvancedConsoleTraceListener 1.0.0' from 'PhpNuget'.
  GET http://192.168.0.14:90/api/v2/package/AdvancedConsoleTraceListener/1.0.0
  OK http://192.168.0.14:90/api/v2/package/AdvancedConsoleTraceListener/1.0.0 5ms
Installing AdvancedConsoleTraceListener 1.0.0.

=> the nuget is added properly to the solution

If you have an idea of what to check 
Thanks

**Comment by laurentKTR** [comment]
Ok i have found why
My solution was in 4.5.1 and the nuget in 4.5
=> nothing is displayed

NugetPackageExplorer doesn't filter :&targetFramework=''
VS2017 filters &targetFramework='net451'
